name: Derp Strike
version: 1.1.0
description: Custom plugin for FNG Nation Derps.
author: never2nv
main: me.never2nv.derp.derp
commands:
     derp:
              description: Derp your crosshairs or another player, globally!
              permission: derp.derp
     derpy:
              description: Derp your crosshairs or another player, globally!
              permission: derp.derpy
     starve:
              description: Starve a player or yourself!
              permission: derp.derp
permissions:
  derp.*:
    description: Gives access to all Derp Strike commands
    children:
      derp.derp
      derp.derpy
      derp.starve
  derp.derp:
    description: Allows you to globally derp a player.
    default: op
  derp.derpy:
    description: Allows you to globally derp a player w/ global reply.
    default: op
  derp.starve:
    description: Starve yourself or a player, not to death.
    default: op